import { config } from 'dotenv'
config()

export const ENV_CONFIG = {
  PORT: process.env.PORT as string,
  PASSWORD_SECRET: process.env.PASSWORD_SECRET as string,

  DB_USERNAME: process.env.DB_USERNAME as string,
  DB_PASSWORD: process.env.DB_PASSWORD as string,
  DB_NAME: process.env.DB_NAME as string,
  DB_ACCOUNTS_COLLECTION_NAME: process.env.DB_ACCOUNTS_COLLECTION_NAME as string,
  DB_REFRESH_TOKENS_COLLECTION_NAME: process.env.DB_REFRESH_TOKENS_COLLECTION_NAME as string,
  DB_VIDEO_CATEGORIES_COLLECTION_NAME: process.env.DB_VIDEO_CATEGORIES_COLLECTION_NAME as string,
  DB_VIDEOS_COLLECTION_NAME: process.env.DB_VIDEOS_COLLECTION_NAME as string,
  DB_COMMENTS_COLLECTION_NAME: process.env.DB_COMMENTS_COLLECTION_NAME as string,
  DB_COMMENT_REPLIES_COLLECTION_NAME: process.env.DB_COMMENT_REPLIES_COLLECTION_NAME as string,
  DB_LIKES_COLLECTION_NAME: process.env.DB_LIKES_COLLECTION_NAME as string,
  DB_DISLIKES_COLLECTION_NAME: process.env.DB_DISLIKES_COLLECTION_NAME as string,
  DB_SUBSCRIPTIONS_COLLECTION_NAME: process.env.DB_SUBSCRIPTIONS_COLLECTION_NAME as string,
  DB_POSTS_COLLECTION_NAME: process.env.DB_POSTS_COLLECTION_NAME as string,
  DB_WATCH_HISTORIES_COLLECTION_NAME: process.env.DB_WATCH_HISTORIES_COLLECTION_NAME as string,
  DB_BOOKMARKS_COLLECTION_NAME: process.env.DB_BOOKMARKS_COLLECTION_NAME as string,
  DB_IMAGES_COLLECTION_NAME: process.env.DB_IMAGES_COLLECTION_NAME as string,
  DB_VIDEO_STATUS_COLLECTION_NAME: process.env.DB_VIDEO_STATUS_COLLECTION_NAME as string,
  DB_REPORTS_COLLECTION_NAME: process.env.DB_REPORTS_COLLECTION_NAME as string,
  DB_PLAYLISTS_COLLECTION_NAME: process.env.DB_PLAYLISTS_COLLECTION_NAME as string,
  DB_PLAYLIST_VIDEOS_COLLECTION_NAME: process.env.DB_PLAYLIST_VIDEOS_COLLECTION_NAME as string,
  DB_NOTIFICATIONS_COLLECTION_NAME: process.env.DB_NOTIFICATIONS_COLLECTION_NAME as string,

  JWT_ACCESS_TOKEN_SECRET: process.env.JWT_ACCESS_TOKEN_SECRET as string,
  JWT_REFRESH_TOKEN_SECRET: process.env.JWT_REFRESH_TOKEN_SECRET as string,
  JWT_VERIFY_EMAIL_TOKEN_SECRET: process.env.JWT_VERIFY_EMAIL_TOKEN_SECRET as string,
  JWT_FORGOT_PASSWORD_TOKEN_SECRET: process.env.JWT_FORGOT_PASSWORD_TOKEN_SECRET as string,
  JWT_ACCESS_TOKEN_EXPIRES_IN: process.env.JWT_ACCESS_TOKEN_EXPIRES_IN as string,
  JWT_REFRESH_TOKEN_EXPIRES_IN: process.env.JWT_REFRESH_TOKEN_EXPIRES_IN as string,
  JWT_VERIFY_EMAIL_TOKEN_EXPIRES_IN: process.env.JWT_VERIFY_EMAIL_TOKEN_EXPIRES_IN as string,
  JWT_FORGOT_PASSWORD_TOKEN_EXPIRES_IN: process.env.JWT_FORGOT_PASSWORD_TOKEN_EXPIRES_IN as string,

  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID as string,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY as string,
  AWS_REGION: process.env.AWS_REGION as string,
  SES_FROM_ADDRESS: process.env.SES_FROM_ADDRESS as string,
  AWS_S3_BUCKET_NAME: process.env.AWS_S3_BUCKET_NAME as string
} as const
